// <auto-generated />
namespace DevNet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class AddFavoriteLanguages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddFavoriteLanguages));
        
        string IMigrationMetadata.Id
        {
            get { return "201503012348146_AddFavoriteLanguages"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
